name: deep_focus
description: "A gamified, clean, and highly interactive Pomodoro and Task Management application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: any
  fl_chart: any
  flutter_local_notifications: any
  permission_handler: any
  vibration: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"